repos:
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: "main"
    hooks:
      - id: helm-readme-generator
        pass_filenames: false
        always_run: true
        args: [--readme=README.md, --values=values.yaml]
