{{- if .Values.idpCredentialsSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.idpCredentialsSecret.name }}
  labels:
    {{- include "sqnc-attachment-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.idpCredentialsSecret.fileName }}: |
    [
    {{- range $index, $item := .Values.idpCredentials }}
      {{- if $index }},{{ end }}
      {
        "username": "{{ $item.username }}",
        "secret": "{{ $item.secret }}",
        "owner": "{{ $item.owner }}"
      }
    {{- end }}
    ]
{{- end }} 