annotations:
  category: sqnc
  licenses: Apache-2.0
apiVersion: v2
# renovate: image=digicatapult/sqnc-matchmaker-api
appVersion: v6.2.31
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.27.0
  - condition: keycloak.enabled
    name: keycloak
    repository: https://charts.bitnami.com/bitnami
    version: 24.7.1
  - name: sqnc-node
    alias: node
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - sqnc-node
    version: 7.1.16
    condition: node.enabled
  - name: sqnc-identity-service
    alias: identity
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - sqnc-identity-service
    version: 5.1.36
    condition: identity.enabled
  - name: sqnc-attachment-api
    alias: attachment
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - sqnc-attachment-api
    version: 3.0.21
    condition: attachment.enabled
description: The sqnc-matchmaker-api is a component of the Sequence (SQNC) ledger-based system.
home: https://github.com/digicatapult/sqnc-documentation
icon: https://raw.githubusercontent.com/digicatapult/sqnc-documentation/main/assets/icon.png
keywords:
  - SQNC
maintainers:
  - name: digicatapult  # Digital Catapult
    url: https://github.com/digicatapult/helm-charts
    email: opensource@digicatapult.org.uk
name: sqnc-matchmaker-api
sources:
  - https://github.com/digicatapult/sqnc-matchmaker-api
version: 4.0.107
