node:
  enabled: false

ipfs:
  enabled: true
  image:
    repository: ipfs/kubo
    tag: v0.18.1
    pullPolicy: IfNotPresent
  ipfs:
    initConfig:
      enabled: false
    initKeys:
      enabled: false
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false
  startupProbe:
    enabled: false
  command: []
  args: []
  dscpNode:
    enabled: true
    node:
      chain: dev
      flags:
      - "--rpc-external"
      - "--alice"
      - "--ws-external"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
