apiVersion: v2
name: dscp-api
# renovate: image=digicatapult/dscp-api
appVersion: '4.8.5'
description: A Helm chart for dscp-api
version: '4.8.9'
type: application
dependencies:
  - name: dscp-node
    version: '4.5.5'
    repository: https://digicatapult.github.io/helm-charts/
    condition: dscpNode.enabled
    alias: dscpNode
  - name: dscp-ipfs
    version: '2.9.5'
    repository: https://digicatapult.github.io/helm-charts/
    condition: dscpIpfs.enabled
    alias: dscpIpfs
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
