# fullNameOverride:
config:
  port: 80
  logLevel: info
  accountKey: //Alice
  enableLivenessProbe: true
  substrateStatusPollPeriodMs: 10000
  substrateStatusTimeoutMs: 2000
  ipfsStatusPollPeriodMs: 10000
  ipfsStatusTimeoutMs: 2000
  auth:
    type: NONE
    jwksUri: https://inteli.eu.auth0.com/.well-known/jwks.json
    audience: inteli-dev
    issuer: https://inteli.eu.auth0.com/
    tokenUrl: https://inteli.eu.auth0.com/oauth/token

deployment:
  annotations: {}
  replicaCount: 1

ingress:
  host: "dscp-api.local"
  annotations: {}
  className: ""
  enabled: true
  paths:
    - /v3

service:
  annotations: {}
  enabled: true
  port: 80

image:
  repository: digicatapult/dscp-api
  pullPolicy: IfNotPresent
  tag: 'v5.0.3'

node:
  enabled: false

ipfs:
  enabled: true
  dscpNode:
    enabled: true
