apiVersion: v2
name: wasp-event-service
appVersion: '0.1.0'
description: A Helm chart for wasp-event-service
version: '0.0.10'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: postgresql
    version: '^11.9.10'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: kafka
    version: '20.x.x'
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
