{{- if and .Values.cnpg.enabled .Values.cnpgSecrets.app.create }}
{{- $initdb := .Values.cnpg.cluster.initdb | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veritable-cloudagent.databaseSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: veritable-cloudagent
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ $initdb.owner | b64enc | quote }}
  password: {{ randAlphaNum 36 | b64enc | quote }}
{{- end }}
