{{- if .Values.cnpg.enabled }}
{{- $cluster := .Values.cnpg.cluster | default dict }}
{{- $pgPassword := randAlphaNum 36 | b64enc }}
{{- if and (not $cluster.superuserSecret) $cluster.enableSuperuserAccess -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cnpg-superuser" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: veritable-cloudagent
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ $pgPassword | quote }}
  pgpass: {{ $pgPassword | quote }}
{{- end }}
{{- end }}
