apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ printf "%s-cron" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: openapi-merger
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.historyLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 12 }}
            app.kubernetes.io/component: openapi-merger
          {{- if .Values.cronjob.podAnnotations }}
          annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.cronjob.podAnnotations "context" $) | nindent 12 }}
          {{- end }}
        spec:
          {{- if .Values.cronjob.nodeSelector }}
          nodeSelector: {{-  toYaml .Values.cronjob.nodeSelector | nindent 12  }}
          {{- end }}
          {{- if .Values.cronjob.tolerations }}
          tolerations: {{- toYaml .Values.cronjob.tolerations | nindent 12 }}
          {{- end }}
          {{- include "openapi-merger.imagePullSecrets" . | nindent 10 }}
          restartPolicy: OnFailure
          {{- if .Values.podSecurityContext.enabled }}
          securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumes:
            - name: config
              configMap:
                name: {{ printf "%s-config" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
            - name: output
              emptyDir: {}
          initContainers:
            - name: openapi-merge
              image: {{ include "openapi-merger.cronjob.initImage" . }}
              imagePullPolicy: {{ .Values.cronjob.initImage.pullPolicy | quote }}
              {{- if .Values.containerSecurityContext.enabled }}
              securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 16 }}
              {{- end }}
              command: 
                - sh 
                - -c
                - |
                  npx openapi-merge-cli --config /etc/openapi-merge-cli/openapi-merge.yaml
              env:
                - name: npm_config_cache
                  value: "/tmp/.npm"
              {{- if .Values.cronjob.resources }}
              resources: {{- include "common.tplvalues.render" (dict "value" .Values.cronjob.resources "context" $) | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: config
                  mountPath: /etc/openapi-merge-cli/openapi-merge.yaml
                  subPath: openapi-merge.yaml
                - name: config
                  mountPath: /etc/openapi-merge-cli/base.json
                  subPath: base.json
                - name: output
                  mountPath: /etc/openapi-merge-cli/output
          containers:
            - name: openapi-merger-snapshotter
              image: {{ include "openapi-merger.cronjob.image" . }}
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy | quote }}
              {{- if .Values.containerSecurityContext.enabled }}
              securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 16 }}
              {{- end }}
              {{- if .Values.diagnosticMode.enabled }}
              command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 16 }}
              args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 16 }}
              {{- else }}
              command:
                - sh
                - -c 
                - |
                  curl -X POST -H "Content-Type: application/json" -d @/etc/openapi-merge-cli/output/output.swagger.json http://$HOST:$PORT/set-api-docs
              {{- end }}
              env:
                - name: DEBUG
                  value: {{ ternary "true" "false" (or .Values.image.debug .Values.diagnosticMode.enabled) | quote }}
                - name: HOST
                  value: {{ include "common.names.fullname" . }}
                - name : PORT
                  value: {{ .Values.service.ports.http | quote }} 
              {{- if .Values.cronjob.resources }}
              resources: {{- toYaml .Values.cronjob.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: output
                  mountPath: /etc/openapi-merge-cli/output
