apiVersion: v2
name: dscp-node
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
description: A Helm chart to deploy DSCP nodes
type: application
version: 5.0.0
# renovate: image=digicatapult/dscp-node
appVersion: '8.0.0'
