node:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
userUri: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
externalSqncIpfs:
  host: localhost
  port: 3000
externalSqncIdentity:
  host: localhost
  port: 3000
auth:
  publicUrlPrefix: "http://keycloak.exmaple.com"
  internalUrlPrefix: "http://keycloak.exmaple.com"
keycloak:
  auth:
    clientId: sequence
  httpRelativePath: /auth/
  extraEnvVars:
    - name: KC_HOSTNAME_PATH
      value: /auth/
    - name: KC_HOSTNAME_PORT
      value: "8080"
    - name: KC_HOSTNAME_DEBUG
      value: "true"
  extraStartupArgs: "--import-realm"
  extraVolumes:
    - name: realm-volume
      configMap:
        name: keycloak-realms
  extraVolumeMounts:
    - mountPath: /opt/bitnami/keycloak/data/import
      name: realm-volume
  resourcesPreset: medium
  postgresql:
    enabled: true
    nameOverride: keycloak-postgres
    auth:
      username: bn_keycloak
      password: ""
      postgresPassword: ""
