{{- if and (not .Values.ipfs.existingSecret ) .Values.ipfs.publicKey .Values.ipfs.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.ipfs.publicKey }}
  publicKey: {{ .Values.ipfs.publicKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.ipfs.privateKey }}
  privateKey: {{ .Values.ipfs.privateKey | b64enc | quote }}
  {{- end }}
{{- end }}
