annotations:
  category: sqnc
  licenses: Apache-2.0
apiVersion: v2
# renovate: image=digicatapult/sqnc-identity-service
appVersion: v4.1.8
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.24.0
  - name: sqnc-node
    alias: node
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - sqnc-node
    version: 7.0.1
    condition: node.enabled
description: The sqnc-identity-service is a component of the Sequence (SQNC) ledger-based system.
home: https://github.com/digicatapult/sqnc-documentation
icon: https://raw.githubusercontent.com/digicatapult/sqnc-documentation/main/assets/icon.png
keywords:
  - SQNC
maintainers:
  - name: digicatapult  # Digital Catapult
    url: https://github.com/digicatapult/helm-charts
    email: opensource@digicatapult.org.uk
name: sqnc-identity-service
sources:
  - https://github.com/digicatapult/sqnc-identity-service
version: 5.1.3
