{{ $fullname :=  include "dscp-node.fullname" . }}
{{ $selectorLabels :=  include "dscp-node.selectorLabels" .  }}
{{ $serviceLabels :=  include "dscp-node.serviceLabels" .  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "dscp-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- $selectorLabels | nindent 4 }}
  ports:
    {{- if $.Values.node.substrateApiSidecar.enabled }}
    - port: 8080
      name: api-sidecar
    {{- end }}
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
---
{{range $i := until (.Values.node.replicas | int) }}
{{- if $.Values.node.perNodeServices.createApiService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}
  labels:
    {{- $serviceLabels | nindent 4 }}
    instance: {{ $fullname }}-{{ $i }}
spec:
  type: ClusterIP
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
    - port: 9615
      name: prometheus
{{- end }}
---
{{- if $.Values.node.perNodeServices.createP2pService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-rc-p2p
spec:
  {{ include "dscp-node.serviceType" $ | nindent 2 }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: p2p
      port: 30333
      targetPort: 30333
  {{- if and $.Values.node.collator.isParachain (or (eq $.Values.node.perNodeServices.p2pServiceType "LoadBalancer") (eq $.Values.node.perNodeServices.p2pServiceType "ClusterIP")) }}
    - name: pc-p2p
      port: 30334
      targetPort: 30334
  {{- end }}
{{- end }}
---
{{- if and $.Values.node.collator.isParachain $.Values.node.perNodeServices.createP2pService (eq $.Values.node.perNodeServices.p2pServiceType "NodePort") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $i }}-pc-p2p
spec:
  {{ include "dscp-node.serviceType" $ | nindent 2 }}
  selector:
    {{- $selectorLabels | nindent 4 }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}
  ports:
    - name: pc-p2p
      port: 30334
      targetPort: 30334
{{- end }}
---
{{ end }}
