apiVersion: v2
name: wasp-open-api
appVersion: '0.1.0'
description: A Helm chart for wasp-open-api
version: '0.0.6'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: nginx
    alias: apidocsmockone
    version: '13.x.x'
    repository: https://charts.bitnami.com/bitnami
    condition: apidocsmock.enabled
  - name: nginx
    alias: apidocsmocktwo
    version: '13.x.x'
    repository: https://charts.bitnami.com/bitnami
    condition: apidocsmock.enabled
