annotations:
  category: wasp
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.1.0
dependencies:
  - condition: apiDocsMock.enabled
    name: nginx
    alias: apiDocsMockOne
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
  - condition: apiDocsMock.enabled
    name: nginx
    alias: apiDocsMockTwo
    repository: https://charts.bitnami.com/bitnami
    version: 13.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: The wasp-open-api is a component of the WASP (Wide-Area-Sensor-Platform), an IoT platform designed to normalise and consolidate data from multiple IoT data services into one place.
home: https://github.com/digicatapult/wasp-documentation
icon: https://raw.githubusercontent.com/digicatapult/wasp-documentation/main/assets/icon.png
keywords:
  - IoT
maintainers:
  - name: digicatapult  # Digital Catapult
    url: https://github.com/digicatapult/helm-charts
    email: opensource@digicatapult.org.uk
name: wasp-open-api
sources:
  - https://github.com/digicatapult/wasp-open-api
version: 1.1.0
