apiVersion: v2
name: wasp-thing-service
appVersion: '0.1.0'
description: A Helm chart for WASP Thing Service
version: '0.0.13'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: postgresql
    version: '^11.9.10'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
