node:
  dataVolumeSize: 1Gi
  role: validator
  chain: dev
  flags:
    - "--rpc-external"
    - "--rpc-methods=Unsafe"
    - "--alice"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
    - "--detailed-log-output"
ct:
  blockHeight:
    waitSeconds: 30
  nodeConnection:
    waitSeconds: 30
    minPeerCount: 0
