node:
  dataVolumeSize: 1Gi
  replicas: 3
  enabled: true
  node:
    chain: local
    flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false
