node:
  dataVolumeSize: 1Gi

alice-node:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"

bob-node:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"

charlie-node:
  enabled: true
  node:
    chain: dev
    flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"