node:
  dataVolumeSize: 1Gi
  replicas: 3
  role: validator
  chain: local
  customNodeKey: "0000000000000000000000000000000000000000000000000000000000000001"
  flags:
    - "--rpc-external"
    - "--alice"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-rpc-external"
