{{ $jwtfullname := printf "%s-jwt" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- if not .Values.existingJwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-jwt" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  jwt-secret: {{ include "common.secrets.passwords.manage" (dict "secret" $jwtfullname "key" "jwt-secret" "providedValues" (list "jwtSecret") "context" $) }}
{{- end }}
