node:
  enabled: true
  node:
    chain: dev
    flags:
      - "--rpc-external"
      - "--alice"
      - "--rpc-methods=Unsafe"
      - "--rpc-cors=all"
      - "--unsafe-rpc-external"
selfAddress: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
auth:
  publicIdpOrigin: "http://keycloak.exmaple.com"
  internalIdpOrigin: "http://keycloak.exmaple.com"
