logLevel: trace
postgresql:
  enabled: false
externalDatabase:
  host: postgres-postgresql.default.svc.cluster.local
  port: 5432
  user: identity_service
  password: test-password
  database: user
  postgresPassword: test-password
  postgresqlPostgresPassword: test-password

node:
  enabled: false
externalSqncNode:
  host: "sqnc-node.default.svc.cluster.local"
  port: "9944"
auth:
  clientId: "sequence"
  publicIdpOrigin: "http://keycloak.default.svc.cluster.local:8080/realms/sequence/protocol/openid-connect"
  internalIdpOrigin: "http://keycloak.default.svc.cluster.local:8080/realms/sequence/protocol/openid-connect"
  tokenPath: "/token"
  jwksPath: "/certs"
