postgresql:
  enabled: false

externalDatabase:
  host: postgres-postgresql.default.svc.cluster.local
  port: 5432
  user: identity_service
  database: user
  existingSecret: my-external-db-secret
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: postgres-password

node:
  enabled: false
externalSqncNode:
  host: "sqnc-node.default.svc.cluster.local"
  port: "9944"
