global:
  postgresql:
    auth:
      username: "global_identity_service"
      database: "global_user"

postgresql:
  enabled: true
  auth:
    username: "local_identity_service"
    database: "local_user"

node:
  enabled: true
  node:
    chain: dev
    flags:
      - "--alice"
      - "--rpc-external"
