logLevel: trace

postgresql:
  enabled: false
externalDatabase:
  host: postgres-postgresql.default.svc.cluster.local
  port: 5432
  user: identity_service
  password: test-password
  database: user
  postgresPassword: postgres-password
  postgresqlPostgresPassword: postgres-password

node:
  enabled: false
