annotations:
  category: dscp
  licenses: Apache-2.0
apiVersion: v2
name: dscp-ipfs
description: dscp-ipfs is a component of the DSCP project that provides a distributed IPFS based storage solution for the DSCP platform.
# renovate: image=digicatapult/dscp-ipfs
appVersion: 2.9.32
version: 3.0.7
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - name: dscp-node
    alias: dscpNode
    repository: https://digicatapult.github.io/helm-charts/
    tags:
      - dscp-node
    version: 5.x.x
    condition: dscpNode.enabled
home: https://github.com/digicatapult/dscp-documentation
icon: https://raw.githubusercontent.com/digicatapult/dscp-documentation/main/assets/icon.png
keywords:
  - DSCP
maintainers:
  - name: digicatapult  # Digital Catapult
    url: https://github.com/digicatapult/helm-charts
    email: opensource@digicatapult.org.uk
sources:
  - https://github.com/digicatapult/dscp-ipfs
