postgresql:
  enabled: true
  auth:
    database: users
    username: users
    password: postgres
replicaCount: 1
config:
  port: 80
  logLevel: info
  authServiceHost: wasp-authentication-service
  authServicePort: 80
  authServiceApiVersion: v1
  authTokenName: Login
  authTokenExpiryDays: 1
  dbName: users
  dbPort: 5432
  externalPostgresql: null
  init:
    dbMigration:
      enabled: true
    adminPassword:
      enabled: false
      logLevel: info
      password: null

image:
  repository: digicatapult/wasp-user-service
  pullPolicy: IfNotPresent
  tag: 'v0.1.0'
ingress:
  paths:
    - /v1/login
  authenticatedPaths:
    - /v1/user
