name: Linting & Integration tests matrix

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "charts/sqnc-identity-service/**"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CHART_LIST: ""
  # space separated list of charts that we want to use a pullSecret for

jobs:
  # make a matrix job that passes the values and sends them as an output to the ct install below where we have this --values=values.yaml
  # extra values files under workflows
  helm-testing-matrix:
    runs-on: ubuntu-latest
    strategy:
      # continue with all the other jobs even if one fails
      fail-fast: false
      matrix:
        # each item in this list is a job with an isolated test VM
        test_cases:
          - name: "Default - no custom values"
            helm_args: ""
          - name: "Tests file values01.yaml"
            helm_args: '--helm-extra-set-args "--set postgresql.enabled=false --set node.enabled=false --set externalDatabase.host=postgres-postgresql --set externalDatabase.port=5432 --set externalDatabase.user=identity_service --set externalDatabase.password=test-password --set externalDatabase.database=user"'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Install additional Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add digicatapult https://digicatapult.github.io/helm-charts

      # only keep changed logic get rid of named_charts logic
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch || 'main' }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: |
          ct lint \
            --target-branch ${{ github.event.repository.default_branch }}
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@v1
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install dependencies postgress and sqnc-node manually
        if: |
          matrix.test_cases.values_file=='charts/sqnc-identity-service/ci/values01.yaml' &&
          steps.list-changed.outputs.changed == 'true'
        run: |
          helm install postgres oci://registry-1.docker.io/bitnamicharts/postgresql \
            --version 12.1.9 \
            --set auth.username=identity_service \
            --set auth.password= \
            --set auth.database=user \
            --set architecture=standalone \
            --wait

            kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=postgresql --timeout=300s

          helm install sqnc-node ./charts/sqnc-node \
            --set fullnameOverride=sqnc-node \
            --set service.port=9944 \
            --set persistence.enabled=true \
            --wait

            kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=sqnc-node --timeout=300s

      - name: Run chart-testing (install)
        run: |
          ct install \
              --target-branch ${{ github.event.repository.default_branch }} \
              --helm-extra-args "--values ${{ matrix.test_cases.helm_args }}"
        if: steps.list-changed.outputs.changed == 'true'
