kafka:
  enabled: true
config:
  waspRoutingServicePort: 3002
  logLevel: 'info'
  kafkaLogLevel: 'info'
  waspThingsHost: things
  waspThingsPort: 80
  rawPayloadsReplicationFactor: 1
  rawPayloadsPartitions: 5
image:
  repository: digicatapult/wasp-routing-service
  pullPolicy: IfNotPresent
  tag: 'v2.1.0'
