{{- if and .Values.cnpg.enabled .Values.cnpgSecrets.superuser.create .Values.cnpg.cluster.enableSuperuserAccess -}}
{{- $pgPassword := randAlphaNum 36 | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veritable-ui.databaseSuperuserSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: veritable-ui
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ $pgPassword | quote }}
  pgpass: {{ $pgPassword | quote }}
{{- end }}
