kafka:
  enabled: false
config:
  port: 80
  logLevel: info
  wsPingIntervalMs: 500
  kafkaLogLevel: 'nothing'
  kafkaBrokers: 'kafka:9092'
  kafkaNotificationReadingsTopic: reading-notifications
  notificationsReplicationFactor: 1
  notificationsPartitions: 5
image:
  repository: digicatapult/wasp-ws-reading-service
  pullPolicy: IfNotPresent
  tag: 'v0.1.0'
kafkaInit:
  repository: bitnami/kafka
  tag: '3.3-debian-11'
ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
  paths:
    - /thing/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/dataset/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/reading
